#+TITLE: Software Complexity

I don't really hate all software, but over the years, a growing exasperation
with the complexity of software sometimes wears me down.

Unnecessary complexity comes with:

  - Breaking continuity (well described in [[https://itnext.io/the-origin-of-complexity-8ecb39130fc][The origin of complexity]])
  - Premature abstraction

I think the most insidious and frustrating source of complexity is premature
abstraction. That is, trying to generalize things too early in the
implementation process. This is more often a problem when using object-oriented
languages, because people feel the need to create object hierarchies that will
absorb future expansion as features are implemented.

Abstraction and the ability to absorb future changes is often discussed as a
"best practice", and there is plenty of literature to back that up, making it
hard to argue against.

One has to understand that a bad abstraction is far worse than no abstraction at
all. *FAR WORSE*. There is often nothing wrong with *not* abstracting things
until you actually need the abstraction for some specific reason.
