#+TITLE: Curating Important Artifacts

* Artifacts

  "Artifact" is an overloaded term. I think of an /artifact/ as a single-file
  resource that is the product of building a project.

  Artifacts are often binaries, like jars for the JVM or native binaries built
  from =go build= or =cargo build=. Interpreted languages also usually specify
  some kind of single-file package format, which may just be a bunch of source
  code zipped up into one file with some metadata (like a python =pip= packages
  build with =sdist=). These single-file packages are "artifacts".

* Artifact Repository

  An Artifact Repository stores artifacts so that you have them all in one
  place.

* Artifact Repository Manager

  A good ARM will know the protocols of popular package managers, so that
  you can store javascript packages in an NPM repo and =npm install= them, or
  store =.deb= artifacts in a =deb= repo and =apt-get install= them, etc.

  Artifactory
  Clarive

* Curating Artifacts

  Some artifacts are more important than others.

  At some point you will need a way to keep track of notable artifacts.
